### PR TITLE
Support external ressources cache check

### PR DESCRIPTION
**Pull request by andreitic**
New steps to support external resources browser cache check, this can be useful when using private CDNs.

- Check for a specific host
`browser cache must be enabled from "([^"]*)" (png|jpeg|gif|ico|js|css) resources`
- Check for self hosted only, same behaviour as the old one
`browser cache must be enabled for (png|jpeg|gif|ico|js|css) self hosted resources`
- Check for any host 
`browser cache must be enabled for (png|jpeg|gif|ico|js|css) resources`

### CODE REVIEW

**Comment by marcortola** [comment]
Thank you for your contribution! It looks like a super useful feature.

What do you think about defining an only step? I'm thinking about something like this:
`@Then /^browser cache must be enabled for (.+\..+|external|internal) (png|jpeg|gif|ico|js|css) resources$`

Thank you again!

**Comment by marcortola** [comment]
Thanks for your efforts, Andrei. You have done such a great job.
I will try to review and merge it in the next weeks.

**Comment by andreitic** [comment]
Perfect, waiting for your input.

**Comment by andreitic** [comment]
Hi @mortola ,
did you had a chance to take a look at the PR?
Thanks

**Comment by marcortola** [comment]
I'm sorry I couldn't review it faster. I have just merged it.

Thank you for your contribution!

**Pull request merged**
