### PR TITLE
Update SitemapContext.php

### LINKED ISSUE #5: Add step to check given number of random sitemap URLs
`@Then the sitemap URLs are alive` can become a pretty time-consuming step given a huge sitemap of let's say 1000 URLs.

Let's add a step that checks only a given number of random URLs to reduce the time this step will take.

### PR DESCRIPTION
**Pull request by normanlolx**
Rerolling #6, closes #5.

This time I introduced `urlIsValid()` and `urlIsAlive()` to keep things DRY.

### CODE REVIEW

**Comment by marcortola** [comment]
@leymannx thanks for the PR! I'll soon add some tests.

**Comment by normanlolx** [comment]
Ah yes, I forgot the tests! Would be nice you adding them. 🙇

**Comment by normanlolx** [comment]
Ah damn, I also forgot the README!

**Comment by marcortola** [comment]
The README and the tests are now ready. 

I've changed the step name to this ``Then /^(\d+) random sitemap URLs? should be alive$/`` to make it look more natural. Thank you again for your contribution!

**Comment by normanlolx** [comment]
Cool! Thanks Marc!

**Pull request merged**
